###
###  TELCO Customer Churn - Exploratory Data Analysis
###
###
###

In [1]:
# Import required Python Libraries

import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
#from ydata_profiling import ProfileReport
from data_profiling import ProfileReport


pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [2]:
# import source data

src = pd.read_excel("Telco_Customer_Churn.xlsx", sheet_name="Telco_Customer_Churn", header=0)

display(src.head(3))
display("Numbsr of Rows and Columns in Dataframe: ", src.shape)  # (7043, 21)
display(src.info())

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes

'Numbsr of Rows and Columns in Dataframe: '

(7043, 21)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

None

"""
Pandas Profiling (now officially known as YData Profiling) is a Python library that automates Exploratory Data Analysis (EDA). 
With just a few lines of code, it generates a detailed interactive report covering :

   missing values, 
   data distributions, 
   correlations, and 
   basic statistics.
pip install ydata-profiling  now 
pip install fg-data-profiling
# Before
import ydata_profiling
from ydata_profiling import ProfileReport

# After
import data_profiling
from data_profiling import ProfileReport

usage:
from ydata_profiling import ProfileReport
### Create the profiling report object
profile = ProfileReport(df, title="Dataset Profiling Report", explorative=True)
### Export to an HTML file
profile.to_file("output_report.html")

### Display the report as an interactive iframe
profile.to_notebook_iframe()

### Alternatively, display it using widgets
profile.to_widgets()
### Minimal Mode: For very large datasets, generating all detailed statistics can take a while. 
### You can disable expensive computations by passing minimal=True
profile = ProfileReport(df, minimal=True)

"""

In [3]:
# Generate Profile report object
profile = ProfileReport(src, title="Telco Customer Churn Data Profiling Report", explorative=True)
#Export to an HTML file
profile.to_file("Telco Customer Churn Source Data Profiling Report.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████████████████████████████████████████| 21/21 [00:00<00:00, 376.24it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [4]:
# Display the report as an interactive iframe
profile.to_notebook_iframe()

In [5]:
df = src.copy()
print(df.shape)

(7043, 21)

In [6]:

# Replacing blanks with 0 in totalcharges column as its tenure is 0 and 
# its loaded as object so we converted as float

df['TotalCharges']= df['TotalCharges'].replace(" ", "0")
df['TotalCharges'] = df['TotalCharges'].astype('float')

In [8]:
# total null count in data

print(df.isnull().sum().sum())

0

In [9]:
display(df.describe())

       SeniorCitizen       tenure  MonthlyCharges  TotalCharges
count    7043.000000  7043.000000     7043.000000   7043.000000
mean        0.162147    32.371149       64.761692   2279.734304
std         0.368612    24.559481       30.090047   2266.794470
min         0.000000     0.000000       18.250000      0.000000
25%         0.000000     9.000000       35.500000    398.550000
50%         0.000000    29.000000       70.350000   1394.550000
75%         0.000000    55.000000       89.850000   3786.600000
max         1.000000    72.000000      118.750000   8684.800000